export const AnnotationStyleStatus = {
    NO_TERM: 'NO_TERM',
    MULTIPLE_TERMS: 'MULTIPLE_TERMS',
    CLUSTER: 'CLUSTER',
    NOT_REVIEWED: 'NOT_REVIEWED',
    REVIEWED: 'REVIEWED',
    HIDDEN: 'HIDDEN'
};
